#!/usr/bin/env python
import sys, math

try:
    input_file = sys.argv[1];  output_file = sys.argv[2]
except:
    print "Usage:",sys.argv[0], "infile outfile"
    sys.exit(1)
    
ifile = open(input_file, 'r')  
ofile = open(output_file, 'w')  

def convert_f_to_c(y):
    zz=(y-32)/1.8
    return zz
    
# read ifile line by line and write out transformed values:
for line in ifile:
    pair = line.split()
    depth = float(pair[0]); temp = float(pair[1])
    ctemp = convert_f_to_c(temp)  
    ofile.write('%g  %4.2f\n' % (depth,ctemp))
ifile.close();  ofile.close()
